// Copyright (c) 2010-2011, Informatica Corporation, Joshua Maurice
//       Distributed under the 3-clause BSD License
//      (See accompanying file LICENSE.TXT or copy at
//  http://www.w3.org/Consortium/Legal/2008/03-bsd-license.html)

#ifndef JUNICODE_JSTRINGLITERAL_HPP_HEADER_GUARD
#define JUNICODE_JSTRINGLITERAL_HPP_HEADER_GUARD

#include "jbase/jstaticassert.hpp"

//Assert that string literals are encoded in ASCII: 
JSTATICASSERT(0 == '\0');
JSTATICASSERT(9 == '\t');
JSTATICASSERT(10 == '\n');
JSTATICASSERT(13 == '\r');
JSTATICASSERT(32 == ' ');
JSTATICASSERT(33 == '!');
JSTATICASSERT(34 == '\"');
JSTATICASSERT(35 == '#');
JSTATICASSERT(36 == '$');
JSTATICASSERT(37 == '%');
JSTATICASSERT(38 == '&');
JSTATICASSERT(39 == '\'');
JSTATICASSERT(40 == '(');
JSTATICASSERT(41 == ')');
JSTATICASSERT(42 == '*');
JSTATICASSERT(43 == '+');
JSTATICASSERT(44 == ',');
JSTATICASSERT(45 == '-');
JSTATICASSERT(46 == '.');
JSTATICASSERT(47 == '/');
JSTATICASSERT(48 == '0');
JSTATICASSERT(49 == '1');
JSTATICASSERT(50 == '2');
JSTATICASSERT(51 == '3');
JSTATICASSERT(52 == '4');
JSTATICASSERT(53 == '5');
JSTATICASSERT(54 == '6');
JSTATICASSERT(55 == '7');
JSTATICASSERT(56 == '8');
JSTATICASSERT(57 == '9');
JSTATICASSERT(58 == ':');
JSTATICASSERT(59 == ';');
JSTATICASSERT(60 == '<');
JSTATICASSERT(61 == '=');
JSTATICASSERT(62 == '>');
JSTATICASSERT(63 == '?');
JSTATICASSERT(64 == '@');
JSTATICASSERT(65 == 'A');
JSTATICASSERT(66 == 'B');
JSTATICASSERT(67 == 'C');
JSTATICASSERT(68 == 'D');
JSTATICASSERT(69 == 'E');
JSTATICASSERT(70 == 'F');
JSTATICASSERT(71 == 'G');
JSTATICASSERT(72 == 'H');
JSTATICASSERT(73 == 'I');
JSTATICASSERT(74 == 'J');
JSTATICASSERT(75 == 'K');
JSTATICASSERT(76 == 'L');
JSTATICASSERT(77 == 'M');
JSTATICASSERT(78 == 'N');
JSTATICASSERT(79 == 'O');
JSTATICASSERT(80 == 'P');
JSTATICASSERT(81 == 'Q');
JSTATICASSERT(82 == 'R');
JSTATICASSERT(83 == 'S');
JSTATICASSERT(84 == 'T');
JSTATICASSERT(85 == 'U');
JSTATICASSERT(86 == 'V');
JSTATICASSERT(87 == 'W');
JSTATICASSERT(88 == 'X');
JSTATICASSERT(89 == 'Y');
JSTATICASSERT(90 == 'Z');
JSTATICASSERT(91 == '[');
JSTATICASSERT(92 == '\\');
JSTATICASSERT(93 == ']');
JSTATICASSERT(94 == '^');
JSTATICASSERT(95 == '_');
JSTATICASSERT(96 == '`');
JSTATICASSERT(97 == 'a');
JSTATICASSERT(98 == 'b');
JSTATICASSERT(99 == 'c');
JSTATICASSERT(100 == 'd');
JSTATICASSERT(101 == 'e');
JSTATICASSERT(102 == 'f');
JSTATICASSERT(103 == 'g');
JSTATICASSERT(104 == 'h');
JSTATICASSERT(105 == 'i');
JSTATICASSERT(106 == 'j');
JSTATICASSERT(107 == 'k');
JSTATICASSERT(108 == 'l');
JSTATICASSERT(109 == 'm');
JSTATICASSERT(110 == 'n');
JSTATICASSERT(111 == 'o');
JSTATICASSERT(112 == 'p');
JSTATICASSERT(113 == 'q');
JSTATICASSERT(114 == 'r');
JSTATICASSERT(115 == 's');
JSTATICASSERT(116 == 't');
JSTATICASSERT(117 == 'u');
JSTATICASSERT(118 == 'v');
JSTATICASSERT(119 == 'w');
JSTATICASSERT(120 == 'x');
JSTATICASSERT(121 == 'y');
JSTATICASSERT(122 == 'z');
JSTATICASSERT(123 == '{');
JSTATICASSERT(124 == '|');
JSTATICASSERT(125 == '}');
JSTATICASSERT(126 == '~');

#endif
